// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.924
package templ

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Error404() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><title>404 - Page Not Found</title><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"><link rel=\"stylesheet\" type=\"text/css\" href=\"/static/styles.css\"><style>\n\t\t\t\tbody {\n\t\t\t\t\tfont-family: Arial, Helvetica, sans-serif;\n\t\t\t\t\ttext-align: center;\n\t\t\t\t\tpadding: 50px;\n\t\t\t\t}\n\t\t\t\t.error-code {\n\t\t\t\t\tfont-size: 120px;\n\t\t\t\t\tfont-weight: bold;\n\t\t\t\t\tcolor: #ff6b6b;\n\t\t\t\t\tmargin: 0;\n\t\t\t\t}\n\t\t\t\t.error-message {\n\t\t\t\t\tfont-size: 24px;\n\t\t\t\t\tcolor: #666;\n\t\t\t\t\tmargin: 20px 0;\n\t\t\t\t}\n\t\t\t\t.home-link {\n\t\t\t\t\tdisplay: inline-block;\n\t\t\t\t\tpadding: 10px 20px;\n\t\t\t\t\tbackground-color: #007bff;\n\t\t\t\t\tcolor: white;\n\t\t\t\t\ttext-decoration: none;\n\t\t\t\t\tborder-radius: 5px;\n\t\t\t\t\tmargin-top: 20px;\n\t\t\t\t}\n\t\t\t\t.home-link:hover {\n\t\t\t\t\tbackground-color: #0056b3;\n\t\t\t\t}\n\t\t\t</style></head><body><h1 class=\"error-code\">404</h1><p class=\"error-message\">Oops! The page you're looking for doesn't exist.</p><a href=\"/\" class=\"home-link\">Go Home</a></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
