version: '3.8'

services:
  app:
    build: .
    ports:
      - "9779:8080"
    env_file:
      - .env
    environment:
      - ENV=development
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
    volumes:
      - .:/app
      - /app/bin
      - /app/tmp
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Database service (commented out - uncomment when database is added)
  # db:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_DB: htmx_quickstart
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   restart: unless-stopped

# volumes:
#   postgres_data: